### ISSUE TITLE
Update ESLint

### ISSUE THREAD

**Issue by newswim** [CommonGarden/CommonGarden-IoT#437]
The `.eslintrc` file is pretty out of date.

```sh
# run linter
> yarn lint
$ eslint .
/Users/dm/github/CommonGarden/Grow-IoT/packages/graphql-api/node_modules/cors/.eslintrc:
	Configuration for rule "quotes" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"single"').

Error: /Users/dm/github/CommonGarden/Grow-IoT/packages/graphql-api/node_modules/cors/.eslintrc:
	Configuration for rule "quotes" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"single"').

# the bigger fish to fry
(node:9169) DeprecationWarning: [eslint] The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in /Users/dm/github/CommonGarden/Grow-IoT/.eslintrc)
```

### Improvement plan

1. Update `eslint` in devDependencies, port/replace existing configuration to follow [newer practices](https://eslint.org/docs/user-guide/configuring).

(or) 2. Switch to `prettier`.
- Pro: Widely used, integrates with eslint, format-on-save is the 💩, lots of language support (eg. markdown, graphql schemas, json files...)
- Con: Can be a somewhat 💩-y experience for Vim users (although there's at least one [popular package](https://github.com/prettier/vim-prettier) that looks fine on the surface).

**Comment by JakeHartnell** [comment]
eslint has been updated, we should use it more.
