### ISSUE TITLE
[chore] Fix failing Travis build on <development> branch

### ISSUE THREAD

**Issue by newswim** [CommonGarden/CommonGarden-IoT#440]
This started when the packages were reorganized. Node is trying to import a non-existent file.

See [that red scary warning](https://travis-ci.org/CommonGarden/Grow-IoT/builds/327510486?utm_source=github_status&utm_medium=notification)

**Comment by newswim** [comment]
Created some no-op exports as a temporary workaround. Now just chasing down the last few errors.

<img width="924" alt="screen shot 2018-01-14 at 1 42 29 pm" src="https://user-images.githubusercontent.com/6667096/34920009-6ee87f88-f931-11e7-87a8-7c8dc17e892d.png">

**Comment by newswim** [comment]
This method inside of `Grow.js` is throwing the undefined TypeError.

https://github.com/CommonGarden/Grow-IoT/blob/38e47d0b0b517d4ca23dec4e0f8730e03b4cd939/packages/Grow.js/lib/Grow.js#L190-L209

There seems to be an issue with the `later` library, I'm now getting an error from here:

https://github.com/bunkat/later/blob/5d38cc3779ad0ee42d61675c8209c1e47c07ca93/later.js#L623

**Comment by JakeHartnell** [comment]
I have made some progress on this with #448 (one of the builds is passing).
