### ISSUE TITLE
Rename or differentiate devices in web-UI

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/CommonGarden-IoT#456]
It's currently a bit difficult to tell similar devices apart. Perhaps a "rename device" function in the device settings menu would be helpful.
<img width="480" alt="screen shot 2018-05-26 at 7 54 45 am" src="https://user-images.githubusercontent.com/3916616/40578832-2ec6e35c-60d0-11e8-9938-5def27f638be.png">

**Comment by JakeHartnell** [comment]
Committed and finished. The device name can be updated in settings.
